version: '3.4'

services:
  projectpet.api:
    image: ${DOCKER_REGISTRY-}projectpetapi
    build:
      context: .
      dockerfile: src/ProjectPet.API/Dockerfile
    ports:
    - "8080:8080"
    - "8081:8081"

  projectpet.database:
    image: postgres
    container_name: ProjectPet.database
    environment:
        - POSTGRES_DB=project_pet
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
    ports:
        - "5432:5432"
    volumes:
        - ./postgres-data:/var/lib/postgresql/data

  projectpet.seq:
    image: datalust/seq:latest
    container_name: ProjectPet.seq
    restart: always
    environment:
        - ACCEPT_EULA=Y
    ports:
        - 5341:5341
        - 8078:80

  projectpet.minio:
    image: minio/minio
    container_name: ProjectPet.minio
    command: server --console-address ":9001" /var/lib/minio/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
        - 9000:9000
        - 9001:9001
    volumes:
        - ./minio-data:/var/lib/minio/data
    restart: always
