version: '3.4'

networks:
  ProjectPetNetwork:
    external: true

services:
  projectpet.web:
    container_name: ProjectPet.web
    build:
      args:
        NUGET_USERNAME: ${NUGET_USERNAME}
        NUGET_PASSWORD: ${NUGET_PASSWORD}
      context: .
      dockerfile: src/ProjectPet.Web/Dockerfile
    ports:
        - "8080:8080"
        - "8081:8081"
    volumes:
        - $APPDATA/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
        - $APPDATA/ASP.NET/Https:/home/app/.aspnet/https:ro
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_HTTP_PORTS=8080
        - ASPNETCORE_HTTPS_PORTS=8081
    depends_on:
        - projectpet.database
        - projectpet.seq
    restart: always
    networks:
      - ProjectPetNetwork
      - default

  projectpet.database:
    image: postgres
    container_name: ProjectPet.database
    environment:
        - POSTGRES_DB=project_pet
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
    ports:
        - "5432:5432"
    volumes:
        - ./postgres-data:/var/lib/postgresql/data
    restart: always

  projectpet.seq:
    image: datalust/seq:latest
    container_name: ProjectPet.seq
    restart: always
    environment:
        - ACCEPT_EULA=Y
    ports:
        - "5341:5341"
        - "8078:80"

  projectpet.nginx:
    image: nginx
    container_name: ProjectPet.nginx
    volumes:
        - ./nginx-config/default.conf:/etc/nginx/conf.d/default.conf
    ports:
        - "80:85"
    depends_on:
        - projectpet.web
    restart: always

  # projectpet.fileservice:
  #   container_name: ProjectPet.fileservice
  #   build:
  #     args:
  #       NUGET_USERNAME: ${NUGET_USERNAME}
  #       NUGET_PASSWORD: ${NUGET_PASSWORD}
  #     context: .
  #     dockerfile: ../ProjectPet.FileService/ProjectPet.FileService/ProjectPet.FileService/Dockerfile
  #   ports:
  #       - "6060:6060"
  #       - "6061:6061"
  #   environment:
  #       - ASPNETCORE_ENVIRONMENT=Development
  #       - ASPNETCORE_HTTP_PORTS=6060
  #       - ASPNETCORE_HTTPS_PORTS=6061
  #   volumes:
  #       - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
  #       - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
  #   depends_on:
  #       - "projectpet.minio"

  # projectpet.minio:
  #   image: minio/minio
  #   container_name: ProjectPet.fileservice.minio
  #   command: server --address ":5000" --console-address ":5001" /var/lib/minio/data
  #   environment:
  #     MINIO_ROOT_USER: minioadmin
  #     MINIO_ROOT_PASSWORD: minioadmin
  #   ports:
  #       - "5000:5000"
  #       - "5001:5001"
  #   volumes:
  #       - ./minio-data:/var/lib/minio/data
